


words = [
    "apple",
    "banana",
    "cherry",
    "date",
    "elderberry",
    "fig",
    "grape",
    "honeydew",
    "kiwi",
    "lemon",
    "mango",
    "nectarine",
    "orange",
    "pear",
    "quince",
    "raspberry",
    "strawberry",
    "tangerine",
    "watermelon",
    "apricot",
    "blueberry",
    "cantaloupe",
    "dragonfruit",
    "grapefruit",
    "guava",
    "jackfruit",
    "kiwifruit",
    "lime",
    "lychee",
    "papaya",
    "passionfruit",
    "pineapple",
    "plum",
    "pomegranate",
    "starfruit",
    "acorn",
    "butternut",
    "chestnut",
    "hazelnut",
    "pecan",
    "walnut",
    "almond",
    "cashew",
    "macadamia",
    "peanut",
    "pistachio",
    "bean",
    "carrot",
    "celery",
    "corn",
    "cucumber",
    "garlic",
    "lettuce",
    "onion",
    "pepper",
    "potato",
    "pumpkin",
    "radish",
    "spinach",
    "squash",
    "tomato",
    "zucchini",
    "broccoli",
    "cauliflower",
    "green bean",
    "pea",
    "artichoke",
    "asparagus",
    "beet",
    "bell pepper",
    "cabbage",
    "carrot",
    "eggplant",
    "leek",
    "mushroom",
    "onion",
    "potato",
    "spinach",
    "sweet potato",
    "zucchini",
    "avocado",
    "chili pepper",
    "cucumber",
    "olive",
    "pumpkin",
    "squash",
    "tomato",
    "turnip",
    "watercress",
    "water spinach",
    "bamboo shoot",
    "bean sprout",
    "cabbage",
    "carrot",
    "celery",
    "chinese broccoli",
    "chinese cabbage",
    "chinese spinach",
    "cucumber",
    "eggplant",
    "garlic",
    "green onion",
    "mushroom",
    "onion",
    "pepper",
    "potato",
    "pumpkin",
    "spinach",
    "squash",
    "tomato",
    "zucchini",
    "apple",
    "apricot",
    "banana",
    "blackberry",
    "blueberry",
    "boysenberry",
    "cherry",
    "cranberry",
    "currant",
    "date",
    "fig",
    "grape",
    "grapefruit",
    "kiwi",
    "lemon",
    "lime",
    "mango",
    "nectarine",
    "orange",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "persimmon",
    "pineapple",
    "plum",
    "pomegranate",
    "raspberry",
    "strawberry",
    "tangerine",
    "watermelon",
    "black bean",
    "black-eyed pea",
    "chickpea",
    "green bean",
    "green pea",
    "kidney bean",
    "lentil",
    "lima bean",
    "navy bean",
    "pinto bean",
    "soybean",
    "almond",
    "cashew",
    "chestnut",
    "coconut",
    "hazelnut",
    "macadamia nut",
    "peanut",
    "pecan",
    "pine nut",
    "pistachio",
    "walnut",
    "beef",
    "chicken",
    "duck",
    "goose",
    "lamb",
    "pork",
    "turkey",
    "bacon",
    "ham",
    "sausage",
    "beef jerky",
    "hot dog",
    "burger",
    "steak",
    "meatball",
    "meatloaf",
    "chicken nugget",
    "chicken wing",
    "chicken leg",
    "chicken breast",
    "drumstick",
    "duck leg",
    "lamb chop",
    "pork chop",
    "pork belly",
    "turkey leg",
    "bacon strip",
    "ham slice",
    "sausage link",
    "beef patty",
    "steak fillet",
    "fish",
    "salmon",
    "tuna",
    "trout",
    "cod",
    "bass",
    "catfish",
    "carp",
    "perch",
    "pike",
    "walleye",
    "mackerel",
    "sardine",
    "anchovy",
    "herring",
    "swordfish",
    "halibut",
    "sole",
    "snapper",
    "grouper",
    "tilapia",
    "mahi-mahi",
    "shellfish",
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "clam",
    "mussel",
    "oyster",
    "scallop",
    "squid",
    "octopus",
    "snail",
    "frog legs",
    "caviar",
    "roe",
    "sea urchin",
    "abalone",
    "escargot",
    "milk",
    "butter",
    "cheese",
    "yogurt",
    "cream",
    "ice cream",
    "sour cream",
    "whipped cream",
    "margarine",
    "mayonnaise",
    "ketchup",
    "mustard",
    "relish",
    "soy sauce",
    "barbecue sauce",
    "steak sauce",
    "hot sauce",
    "ranch dressing",
    "italian dressing",
    "thousand island dressing",
    "salsa",
    "guacamole",
    "hummus",
    "peanut butter",
    "jelly",
    "jam",
    "honey",
    "maple syrup",
    "molasses",
    "chocolate syrup",
    "whipped cream",
    "marshmallow",
    "candy",
    "gum",
    "caramel",
    "toffee",
    "fudge",
    "brittle",
    "nougat",
    "licorice",
    "taffy",
    "rock candy",
    "lollipop",
    "jawbreaker",
    "bubblegum",
    "gummy bear",
    "chocolate",
    "milk chocolate",
    "dark chocolate",
    "white chocolate",
]